
package com.sf.kyc.vas.soap.webservice.artifact;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.8
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "AirService", targetNamespace = "http://tempuri.org/", wsdlLocation = "http://172.24.35.96:2015/air.svc?wsdl")
public class AirService
    extends Service
{

    private final static URL AIRSERVICE_WSDL_LOCATION;
    private final static WebServiceException AIRSERVICE_EXCEPTION;
    private final static QName AIRSERVICE_QNAME = new QName("http://tempuri.org/", "AirService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://172.24.35.96:2015/air.svc?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        AIRSERVICE_WSDL_LOCATION = url;
        AIRSERVICE_EXCEPTION = e;
    }

    public AirService() {
        super(__getWsdlLocation(), AIRSERVICE_QNAME);
    }

    public AirService(WebServiceFeature... features) {
        super(__getWsdlLocation(), AIRSERVICE_QNAME, features);
    }

    public AirService(URL wsdlLocation) {
        super(wsdlLocation, AIRSERVICE_QNAME);
    }

    public AirService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, AIRSERVICE_QNAME, features);
    }

    public AirService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public AirService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns IAirService
     */
    @WebEndpoint(name = "BasicHttpBinding_IAirService")
    public IAirService getBasicHttpBindingIAirService() {
        return super.getPort(new QName("http://tempuri.org/", "BasicHttpBinding_IAirService"), IAirService.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns IAirService
     */
    @WebEndpoint(name = "BasicHttpBinding_IAirService")
    public IAirService getBasicHttpBindingIAirService(WebServiceFeature... features) {
        return super.getPort(new QName("http://tempuri.org/", "BasicHttpBinding_IAirService"), IAirService.class, features);
    }

    private static URL __getWsdlLocation() {
        if (AIRSERVICE_EXCEPTION!= null) {
            throw AIRSERVICE_EXCEPTION;
        }
        return AIRSERVICE_WSDL_LOCATION;
    }

}
