
package com.sf.kyc.vas.soap.webservice.artifact;

import java.math.BigDecimal;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.datatype.XMLGregorianCalendar;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.8
 * Generated source version: 2.2
 * 
 */
@WebService(name = "IAirService", targetNamespace = "http://tempuri.org/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface IAirService {


    /**
     * 
     * @param amount
     * @param msisdn
     * @param externalData1
     * @return
     *     returns java.lang.Boolean
     */
    @WebMethod(operationName = "AdjustBalance", action = "http://tempuri.org/IAirService/AdjustBalance")
    @WebResult(name = "AdjustBalanceResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "AdjustBalance", targetNamespace = "http://tempuri.org/", className = "com.sf.kyc.vas.soap.webservice.artifact.AdjustBalance")
    @ResponseWrapper(localName = "AdjustBalanceResponse", targetNamespace = "http://tempuri.org/", className = "com.sf.kyc.vas.soap.webservice.artifact.AdjustBalanceResponse")
    public Boolean adjustBalance(
        @WebParam(name = "msisdn", targetNamespace = "http://tempuri.org/")
        String msisdn,
        @WebParam(name = "amount", targetNamespace = "http://tempuri.org/")
        BigDecimal amount,
        @WebParam(name = "externalData1", targetNamespace = "http://tempuri.org/")
        String externalData1);

    /**
     * 
     * @param msisdn
     * @return
     *     returns com.sf.kyc.vas.soap.webservice.artifact.AccountDetails
     */
    @WebMethod(operationName = "GetAccountDetails", action = "http://tempuri.org/IAirService/GetAccountDetails")
    @WebResult(name = "GetAccountDetailsResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "GetAccountDetails", targetNamespace = "http://tempuri.org/", className = "com.sf.kyc.vas.soap.webservice.artifact.GetAccountDetails")
    @ResponseWrapper(localName = "GetAccountDetailsResponse", targetNamespace = "http://tempuri.org/", className = "com.sf.kyc.vas.soap.webservice.artifact.GetAccountDetailsResponse")
    public AccountDetails getAccountDetails(
        @WebParam(name = "msisdn", targetNamespace = "http://tempuri.org/")
        String msisdn);

    /**
     * 
     * @param msisdn
     * @return
     *     returns com.sf.kyc.vas.soap.webservice.artifact.AccumulatorDetails
     */
    @WebMethod(operationName = "GetAccumulatorDetails", action = "http://tempuri.org/IAirService/GetAccumulatorDetails")
    @WebResult(name = "GetAccumulatorDetailsResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "GetAccumulatorDetails", targetNamespace = "http://tempuri.org/", className = "com.sf.kyc.vas.soap.webservice.artifact.GetAccumulatorDetails")
    @ResponseWrapper(localName = "GetAccumulatorDetailsResponse", targetNamespace = "http://tempuri.org/", className = "com.sf.kyc.vas.soap.webservice.artifact.GetAccumulatorDetailsResponse")
    public AccumulatorDetails getAccumulatorDetails(
        @WebParam(name = "msisdn", targetNamespace = "http://tempuri.org/")
        String msisdn);

    /**
     * 
     * @param msisdn
     * @return
     *     returns java.lang.Integer
     */
    @WebMethod(operationName = "GetServiceClass", action = "http://tempuri.org/IAirService/GetServiceClass")
    @WebResult(name = "GetServiceClassResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "GetServiceClass", targetNamespace = "http://tempuri.org/", className = "com.sf.kyc.vas.soap.webservice.artifact.GetServiceClass")
    @ResponseWrapper(localName = "GetServiceClassResponse", targetNamespace = "http://tempuri.org/", className = "com.sf.kyc.vas.soap.webservice.artifact.GetServiceClassResponse")
    public Integer getServiceClass(
        @WebParam(name = "msisdn", targetNamespace = "http://tempuri.org/")
        String msisdn);

    /**
     * 
     * @param msisdn
     * @return
     *     returns com.sf.kyc.vas.soap.webservice.artifact.ArrayOfAccumulator
     */
    @WebMethod(operationName = "GetAccumulators", action = "http://tempuri.org/IAirService/GetAccumulators")
    @WebResult(name = "GetAccumulatorsResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "GetAccumulators", targetNamespace = "http://tempuri.org/", className = "com.sf.kyc.vas.soap.webservice.artifact.GetAccumulators")
    @ResponseWrapper(localName = "GetAccumulatorsResponse", targetNamespace = "http://tempuri.org/", className = "com.sf.kyc.vas.soap.webservice.artifact.GetAccumulatorsResponse")
    public ArrayOfAccumulator getAccumulators(
        @WebParam(name = "msisdn", targetNamespace = "http://tempuri.org/")
        String msisdn);

    /**
     * 
     * @param msisdn
     * @return
     *     returns com.sf.kyc.vas.soap.webservice.artifact.BalanceInfo
     */
    @WebMethod(operationName = "GetBalanceInfo", action = "http://tempuri.org/IAirService/GetBalanceInfo")
    @WebResult(name = "GetBalanceInfoResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "GetBalanceInfo", targetNamespace = "http://tempuri.org/", className = "com.sf.kyc.vas.soap.webservice.artifact.GetBalanceInfo")
    @ResponseWrapper(localName = "GetBalanceInfoResponse", targetNamespace = "http://tempuri.org/", className = "com.sf.kyc.vas.soap.webservice.artifact.GetBalanceInfoResponse")
    public BalanceInfo getBalanceInfo(
        @WebParam(name = "msisdn", targetNamespace = "http://tempuri.org/")
        String msisdn);

    /**
     * 
     * @param msisdn
     * @return
     *     returns com.sf.kyc.vas.soap.webservice.artifact.GetBalanceAndDateResponse2
     */
    @WebMethod(operationName = "GetBalanceAndDate", action = "http://tempuri.org/IAirService/GetBalanceAndDate")
    @WebResult(name = "GetBalanceAndDateResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "GetBalanceAndDate", targetNamespace = "http://tempuri.org/", className = "com.sf.kyc.vas.soap.webservice.artifact.GetBalanceAndDate")
    @ResponseWrapper(localName = "GetBalanceAndDateResponse", targetNamespace = "http://tempuri.org/", className = "com.sf.kyc.vas.soap.webservice.artifact.GetBalanceAndDateResponse")
    public GetBalanceAndDateResponse2 getBalanceAndDate(
        @WebParam(name = "msisdn", targetNamespace = "http://tempuri.org/")
        String msisdn);

    /**
     * 
     * @param msisdn
     * @return
     *     returns com.sf.kyc.vas.soap.webservice.artifact.ArrayOfFafInfo
     */
    @WebMethod(operationName = "GetFaFList", action = "http://tempuri.org/IAirService/GetFaFList")
    @WebResult(name = "GetFaFListResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "GetFaFList", targetNamespace = "http://tempuri.org/", className = "com.sf.kyc.vas.soap.webservice.artifact.GetFaFList")
    @ResponseWrapper(localName = "GetFaFListResponse", targetNamespace = "http://tempuri.org/", className = "com.sf.kyc.vas.soap.webservice.artifact.GetFaFListResponse")
    public ArrayOfFafInfo getFaFList(
        @WebParam(name = "msisdn", targetNamespace = "http://tempuri.org/")
        String msisdn);

    /**
     * 
     * @param state
     * @param msisdn
     * @param serviceId
     * @return
     *     returns java.lang.Boolean
     */
    @WebMethod(operationName = "UpdateSubscriberSegmentation1", action = "http://tempuri.org/IAirService/UpdateSubscriberSegmentation1")
    @WebResult(name = "UpdateSubscriberSegmentation1Result", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "UpdateSubscriberSegmentation1", targetNamespace = "http://tempuri.org/", className = "com.sf.kyc.vas.soap.webservice.artifact.UpdateSubscriberSegmentation1")
    @ResponseWrapper(localName = "UpdateSubscriberSegmentation1Response", targetNamespace = "http://tempuri.org/", className = "com.sf.kyc.vas.soap.webservice.artifact.UpdateSubscriberSegmentation1Response")
    public Boolean updateSubscriberSegmentation1(
        @WebParam(name = "msisdn", targetNamespace = "http://tempuri.org/")
        String msisdn,
        @WebParam(name = "serviceId", targetNamespace = "http://tempuri.org/")
        Integer serviceId,
        @WebParam(name = "state", targetNamespace = "http://tempuri.org/")
        Boolean state);

    /**
     * 
     * @param state
     * @param msisdn
     * @param serviceId
     * @return
     *     returns java.lang.Boolean
     */
    @WebMethod(operationName = "UpdateSubscriberSegmentation2", action = "http://tempuri.org/IAirService/UpdateSubscriberSegmentation2")
    @WebResult(name = "UpdateSubscriberSegmentation2Result", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "UpdateSubscriberSegmentation2", targetNamespace = "http://tempuri.org/", className = "com.sf.kyc.vas.soap.webservice.artifact.UpdateSubscriberSegmentation2")
    @ResponseWrapper(localName = "UpdateSubscriberSegmentation2Response", targetNamespace = "http://tempuri.org/", className = "com.sf.kyc.vas.soap.webservice.artifact.UpdateSubscriberSegmentation2Response")
    public Boolean updateSubscriberSegmentation2(
        @WebParam(name = "msisdn", targetNamespace = "http://tempuri.org/")
        String msisdn,
        @WebParam(name = "serviceId", targetNamespace = "http://tempuri.org/")
        ArrayOfint serviceId,
        @WebParam(name = "state", targetNamespace = "http://tempuri.org/")
        Boolean state);

    /**
     * 
     * @param msisdn
     * @param serviceValues
     * @return
     *     returns java.lang.Boolean
     */
    @WebMethod(operationName = "UpdateSubscriberSegmentation3", action = "http://tempuri.org/IAirService/UpdateSubscriberSegmentation3")
    @WebResult(name = "UpdateSubscriberSegmentation3Result", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "UpdateSubscriberSegmentation3", targetNamespace = "http://tempuri.org/", className = "com.sf.kyc.vas.soap.webservice.artifact.UpdateSubscriberSegmentation3")
    @ResponseWrapper(localName = "UpdateSubscriberSegmentation3Response", targetNamespace = "http://tempuri.org/", className = "com.sf.kyc.vas.soap.webservice.artifact.UpdateSubscriberSegmentation3Response")
    public Boolean updateSubscriberSegmentation3(
        @WebParam(name = "msisdn", targetNamespace = "http://tempuri.org/")
        String msisdn,
        @WebParam(name = "serviceValues", targetNamespace = "http://tempuri.org/")
        ArrayOfKeyValueOfintboolean serviceValues);

    /**
     * 
     * @param identifier
     * @param dedicatedAccountId
     * @param amountRelative
     * @param msisdn
     * @param daysOffset
     * @return
     *     returns java.lang.Boolean
     */
    @WebMethod(operationName = "AdjustDedicatedAccount", action = "http://tempuri.org/IAirService/AdjustDedicatedAccount")
    @WebResult(name = "AdjustDedicatedAccountResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "AdjustDedicatedAccount", targetNamespace = "http://tempuri.org/", className = "com.sf.kyc.vas.soap.webservice.artifact.AdjustDedicatedAccount")
    @ResponseWrapper(localName = "AdjustDedicatedAccountResponse", targetNamespace = "http://tempuri.org/", className = "com.sf.kyc.vas.soap.webservice.artifact.AdjustDedicatedAccountResponse")
    public Boolean adjustDedicatedAccount(
        @WebParam(name = "msisdn", targetNamespace = "http://tempuri.org/")
        String msisdn,
        @WebParam(name = "dedicatedAccountId", targetNamespace = "http://tempuri.org/")
        Integer dedicatedAccountId,
        @WebParam(name = "amountRelative", targetNamespace = "http://tempuri.org/")
        Integer amountRelative,
        @WebParam(name = "daysOffset", targetNamespace = "http://tempuri.org/")
        Integer daysOffset,
        @WebParam(name = "identifier", targetNamespace = "http://tempuri.org/")
        String identifier);

    /**
     * 
     * @param identifier
     * @param dedicatedAccountId
     * @param newAmount
     * @param msisdn
     * @return
     *     returns java.lang.Boolean
     */
    @WebMethod(operationName = "SetDedicatedAccount", action = "http://tempuri.org/IAirService/SetDedicatedAccount")
    @WebResult(name = "SetDedicatedAccountResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "SetDedicatedAccount", targetNamespace = "http://tempuri.org/", className = "com.sf.kyc.vas.soap.webservice.artifact.SetDedicatedAccount")
    @ResponseWrapper(localName = "SetDedicatedAccountResponse", targetNamespace = "http://tempuri.org/", className = "com.sf.kyc.vas.soap.webservice.artifact.SetDedicatedAccountResponse")
    public Boolean setDedicatedAccount(
        @WebParam(name = "msisdn", targetNamespace = "http://tempuri.org/")
        String msisdn,
        @WebParam(name = "dedicatedAccountId", targetNamespace = "http://tempuri.org/")
        Integer dedicatedAccountId,
        @WebParam(name = "newAmount", targetNamespace = "http://tempuri.org/")
        Integer newAmount,
        @WebParam(name = "identifier", targetNamespace = "http://tempuri.org/")
        String identifier);

    /**
     * 
     * @param identifier
     * @param dedicatedAccountId
     * @param newDate
     * @param newAmount
     * @param msisdn
     * @return
     *     returns java.lang.Boolean
     */
    @WebMethod(operationName = "FixDedicatedAccount", action = "http://tempuri.org/IAirService/FixDedicatedAccount")
    @WebResult(name = "FixDedicatedAccountResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "FixDedicatedAccount", targetNamespace = "http://tempuri.org/", className = "com.sf.kyc.vas.soap.webservice.artifact.FixDedicatedAccount")
    @ResponseWrapper(localName = "FixDedicatedAccountResponse", targetNamespace = "http://tempuri.org/", className = "com.sf.kyc.vas.soap.webservice.artifact.FixDedicatedAccountResponse")
    public Boolean fixDedicatedAccount(
        @WebParam(name = "msisdn", targetNamespace = "http://tempuri.org/")
        String msisdn,
        @WebParam(name = "dedicatedAccountId", targetNamespace = "http://tempuri.org/")
        Integer dedicatedAccountId,
        @WebParam(name = "newAmount", targetNamespace = "http://tempuri.org/")
        Integer newAmount,
        @WebParam(name = "newDate", targetNamespace = "http://tempuri.org/")
        XMLGregorianCalendar newDate,
        @WebParam(name = "identifier", targetNamespace = "http://tempuri.org/")
        String identifier);

    /**
     * 
     * @param identifier
     * @param dedicatedAccountId
     * @param newDate
     * @param newAmount
     * @param msisdn
     * @param dedicatedAccountUnitType
     * @return
     *     returns java.lang.Boolean
     */
    @WebMethod(operationName = "FixDedicatedAccountAAPCN", action = "http://tempuri.org/IAirService/FixDedicatedAccountAAPCN")
    @WebResult(name = "FixDedicatedAccountAAPCNResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "FixDedicatedAccountAAPCN", targetNamespace = "http://tempuri.org/", className = "com.sf.kyc.vas.soap.webservice.artifact.FixDedicatedAccountAAPCN")
    @ResponseWrapper(localName = "FixDedicatedAccountAAPCNResponse", targetNamespace = "http://tempuri.org/", className = "com.sf.kyc.vas.soap.webservice.artifact.FixDedicatedAccountAAPCNResponse")
    public Boolean fixDedicatedAccountAAPCN(
        @WebParam(name = "msisdn", targetNamespace = "http://tempuri.org/")
        String msisdn,
        @WebParam(name = "dedicatedAccountId", targetNamespace = "http://tempuri.org/")
        Integer dedicatedAccountId,
        @WebParam(name = "newAmount", targetNamespace = "http://tempuri.org/")
        Integer newAmount,
        @WebParam(name = "newDate", targetNamespace = "http://tempuri.org/")
        XMLGregorianCalendar newDate,
        @WebParam(name = "dedicatedAccountUnitType", targetNamespace = "http://tempuri.org/")
        Integer dedicatedAccountUnitType,
        @WebParam(name = "identifier", targetNamespace = "http://tempuri.org/")
        String identifier);

    /**
     * 
     * @param identifier
     * @param dedicatedAccountId
     * @param amountRelative
     * @param newDate
     * @param msisdn
     * @return
     *     returns java.lang.Boolean
     */
    @WebMethod(operationName = "AdjustDedicatedAccountWithFixedDate", action = "http://tempuri.org/IAirService/AdjustDedicatedAccountWithFixedDate")
    @WebResult(name = "AdjustDedicatedAccountWithFixedDateResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "AdjustDedicatedAccountWithFixedDate", targetNamespace = "http://tempuri.org/", className = "com.sf.kyc.vas.soap.webservice.artifact.AdjustDedicatedAccountWithFixedDate")
    @ResponseWrapper(localName = "AdjustDedicatedAccountWithFixedDateResponse", targetNamespace = "http://tempuri.org/", className = "com.sf.kyc.vas.soap.webservice.artifact.AdjustDedicatedAccountWithFixedDateResponse")
    public Boolean adjustDedicatedAccountWithFixedDate(
        @WebParam(name = "msisdn", targetNamespace = "http://tempuri.org/")
        String msisdn,
        @WebParam(name = "dedicatedAccountId", targetNamespace = "http://tempuri.org/")
        Integer dedicatedAccountId,
        @WebParam(name = "amountRelative", targetNamespace = "http://tempuri.org/")
        Integer amountRelative,
        @WebParam(name = "newDate", targetNamespace = "http://tempuri.org/")
        XMLGregorianCalendar newDate,
        @WebParam(name = "identifier", targetNamespace = "http://tempuri.org/")
        String identifier);

    /**
     * 
     * @param newServiceClass
     * @param identifier
     * @param msisdn
     * @return
     *     returns java.lang.Boolean
     */
    @WebMethod(operationName = "ChangeServiceClass", action = "http://tempuri.org/IAirService/ChangeServiceClass")
    @WebResult(name = "ChangeServiceClassResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "ChangeServiceClass", targetNamespace = "http://tempuri.org/", className = "com.sf.kyc.vas.soap.webservice.artifact.ChangeServiceClass")
    @ResponseWrapper(localName = "ChangeServiceClassResponse", targetNamespace = "http://tempuri.org/", className = "com.sf.kyc.vas.soap.webservice.artifact.ChangeServiceClassResponse")
    public Boolean changeServiceClass(
        @WebParam(name = "msisdn", targetNamespace = "http://tempuri.org/")
        String msisdn,
        @WebParam(name = "newServiceClass", targetNamespace = "http://tempuri.org/")
        Integer newServiceClass,
        @WebParam(name = "identifier", targetNamespace = "http://tempuri.org/")
        String identifier);

    /**
     * 
     * @param voucher
     * @param msisdn
     * @param externalData1
     * @return
     *     returns com.sf.kyc.vas.soap.webservice.artifact.RefillResponse2
     */
    @WebMethod(operationName = "Refill", action = "http://tempuri.org/IAirService/Refill")
    @WebResult(name = "RefillResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "Refill", targetNamespace = "http://tempuri.org/", className = "com.sf.kyc.vas.soap.webservice.artifact.Refill")
    @ResponseWrapper(localName = "RefillResponse", targetNamespace = "http://tempuri.org/", className = "com.sf.kyc.vas.soap.webservice.artifact.RefillResponse")
    public RefillResponse2 refill(
        @WebParam(name = "msisdn", targetNamespace = "http://tempuri.org/")
        String msisdn,
        @WebParam(name = "voucher", targetNamespace = "http://tempuri.org/")
        String voucher,
        @WebParam(name = "externalData1", targetNamespace = "http://tempuri.org/")
        String externalData1);

}
